name: Setup
description: Common workflow setup steps
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        cache: pnpm
        registry-url: "https://registry.npmjs.org"
        scope: "@crosshatch"
    - uses: pnpm/action-setup@v4
    - shell: bash
      run: pnpm install
