name: Setup
description: Workflow setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        cache: pnpm
    - shell: bash
      run: pnpm install
