packages:
  - repo-util

catalog:
  "@effect/cli": ^0.73.1
  "@effect/language-service": 0.73.0
  "@effect/platform": ^0.94.3
  "@effect/platform-node": ^0.104.1
  "@types/node": ^25.2.0
  dedent: ^1.7.1
  dprint: ^0.51.1
  effect: ^3.19.16
  oxlint: ^1.35.0
  ts-patch: ^3.3.0
  typescript: ^5.9.3
  yaml: "^2.8.2"
